[build-system]
requires=["maturin>=1.1,<2.0"]
build-backend="maturin"

[project]
authors=[{ name="ppeter", email="ppeter1@smail.uni-koeln.de" }]
name="mcr_py"
version="0.1.0"
requires-python=">=3.12"
classifiers=[
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Rust",
]
dependencies=[
    "aiohttp>=3.11.11",
    "altair>=5.5.0",
    "folium>=0.19.4",
    "fsspec>=2024.12.0",
    "h3>=4.2.0",
    "ipykernel>=6.29.5",
    "joblib>=1.4.2",
    "jupyter>=1.1.1",
    "kaleido>=1.2.0",
    "kmedoids>=0.5.3.1",
    "matplotlib>=3.10.0",
    "maturin>=1.8.1",
    "networkx>=3.4.2",
    "notebook>=7.3.2",
    "overpass>=0.7.2",
    "pandera[polars]>=0.26.1",
    "patchelf>=0.17.2.1",
    "plotly>=6.4.0",
    "polars-h3>=0.5.1",
    "polars-st>=0.3.0",
    "polars-xdt>=0.16.7",
    "polars>=1.32.0,!=1.32.3,!=1.33.0",
    "pre-commit>=4.0.1",
    "pyarrow>=19.0.0",
    "pyproj>=3.7.1",
    "pyright>1.1.406",
    "pyserde>=0.23.0",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "ruff>=0.11.5",
    "rustworkx>=0.16.0",
    "scienceplots>=2.1.1",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "shapely>=2.0.6",
    "tqdm>=4.67.1",
    "typer>=0.15.1",
    "vl-convert-python>=1.8.0",
]

[tool.maturin]
features=["pyo3/extension-module"]
python-source="python"
module-name="mcr_py._mcr_py"

[tool.ruff]
extend-include=["*.ipynb"]

[tool.pytest.ini_options]
minversion="6.0"
addopts="-ra -q"
testpaths="test"
pythonpath=["."]

[tool.pyright]
venvPath="."
venv=".venv"
