[run_type]
run_type="INFO"

[geography]
crs_sink_name="EPSG:4839"

[timestamp]
# timestamp="20250718"
# timestamp="20250808"
# timestamp="20250905"
timestamp="20250926"
# now="2025-07-18-114512"
# now="2025-08-08-114512"
# now="2025-09-05-143520"
now="20250926-095849"

[gtfs]
timestamp="20250718"

[public_transport]
start_times=["08:02:28"]

[mcr5_types]
mcr5_types=[
    "bicycle",
    "bicycle_public_transport",
    "car",
    "public_transport",
    "public_transport",
    "walking",
]

[city.cologne]
german="K\u00F6ln"
german_alt="Koeln"
gbfs_url="https://gbfs.nextbike.net/maps/gbfs/v1/nextbike_kg/de/free_bike_status.json"
admin_level=6

[city.berlin]
german="Berlin"
german_alt="Berlin"
admin_level=4
